name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Create Docs Directory and Copy Index
        run: |
          mkdir -p docs
          cp readme.md docs/index.md

      - name: Install Dependencies
        run: pip install -r mkdocs-requirements.txt

      - name: Build and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          mkdocs gh-deploy --force --remote-name origin --remote-branch gh-pages --message "Deploy from GitHub Actions"
